# BungeeTabListPlus 2.4.5

# If this is set to true and the plugin encounters an issue a bugreport is sent automatically
# Bug reports do not contain any sensitive or identifying information
# Bug reports contain the plugin name, plugin version and the error message that also appears in the server log
automaticallySendBugReports: true

